### ISSUE TITLE
To change

### ISSUE THREAD

**Issue by firaskrichi** [neilkrichi/coffee-marketplace#10]
Make filepicker button like this : 

`              <button type="button" onClick={this.pickFile}>Choose your img</button>
`

if you put a button inside a form it'll trigger the handleSubmit. That's why we were getting the duplicate coffees. 

So when you add `type='button'` it won't do that. 

Also, the button you're using to submit the form should be this: 

`<button type="submit">Submit</button>
`

You can use `browserHistory.push('/home')` inside handleSubmit instead of <Link> here 

Close this issue as soon as it's done please.

**Comment by neilkrichi** [comment]
done!

**Comment by firaskrichi** [comment]
Wow you're fast

**Comment by neilkrichi** [comment]
it's the Breka effect. another issue: when I add listings ca let met pas dans un ordre chronologique... how can we fix that?

**Comment by firaskrichi** [comment]
I can add a dateCreated and you can filter on that ?

**Comment by neilkrichi** [comment]
ok on peut faire ca!

**Comment by firaskrichi** [comment]
done
